[manifest]
version = "1.2"
dump_lua = true
priority = 0

# Uncomment below if you would like to install this mod
# standalone of Steamodded

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = '''['en-us'] = {font = 1, label = "English", key = 'en-us', button = "Language Feedback", warning = {'This language is still in Beta. To help us','improve it, please click on the feedback button.', 'Click again to confirm'}},'''
# position = "at"
# payload = '''['en-us'] = {font = 1, label = "English", key = 'en-us', button = "Language Feedback", warning = {'This language is still in Beta. To help us','improve it, please click on the feedback button.', 'Click again to confirm'}},
# ['th_TH'] = {font = 6, label = "ไทย", key = 'th_TH', beta = true, button = "ข้อเสนอแนะ", warning = {'ภาษานี้ยังอยู่ในช่วงทดสอบ เพื่อช่วยเรา','ปรับปรุงโปรดคลิกที่ปุ่มข้อเสนอแนะ', 'คลิกอีกครั้งเพื่อยืนยัน'}},'''
# overwrite = true
# match_indent = true

# [[patches]]
# [patches.pattern]
# target = "game.lua"
# pattern = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 1, DESCSCALE = 1},'''
# position = "at"
# payload = '''{file = "assets/fonts/2005_iannnnnAMD.ttf", render_scale = self.TILESIZE*16, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.13, squish = 1, DESCSCALE = 1},'''
# overwrite = true
# match_indent = true


# แก้ไขการอยู่ตรงกลางของปุ่ม "รีเซ็ต"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "tm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
position = "at"
payload = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "cm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
overwrite = true
match_indent = true

# แก้ไขการอยู่ตรงกลางของปุ่ม "ข้าม"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R,config={align = "tm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
position = "at"
payload = '''{n=G.UIT.R,config={align = "cm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
overwrite = true
match_indent = true

# "คะแนนรอบ" แทนที่จะเป็น "รอบคะแนน"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "แต้ม", scale = 0.3, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text =localize('k_lower_score'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "รอบ", scale = 0.3, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true

# แก้ไขขนาดตัวอักษรบนปุ่ม "รอบถัดไป"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", maxw = 1.3}, nodes={'''
position = "at"
payload = '''{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={'''
overwrite = true
match_indent = true

# "ภาพรวมสำรับ" แทนที่จะเป็น "สำรับภาพรวม"
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_deck'), scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "สำรับ", scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

# การแปลและตำแหน่งของบรรทัด "PEEK DECK" เมื่อเล่นกับเกมแพด
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'แอบดู', scale = 0.48, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'ส่วนที่เหลือ", scale = 0.35, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'สำรับ', scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'ไพ่', scale = 0.4, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''config = { align = 'cl', offset = {x=-0.5,y=0.1}, major = self, parent = self}'''
position = "at"
payload = '''config = { align = 'bl', offset = {x=-10.78,y=-1.45}, major = self, parent = self}'''
overwrite = true
match_indent = true

# การแปลสำหรับบรรทัดที่ขาดหายไป "DEFEAT BOSS-BLIND TO RESTOCK"
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''elseif G.SETTINGS.language ~= 'en-us' then'''
position = "at"
payload = '''elseif G.SETTINGS.language == 'zh_TW' then'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'พ่ายแพ้', scale = 0.6, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'พ่ายแพ้', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'บอส บลายด์', scale = 0.4, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'บอส บลายด์', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'DEFEAT', scale = 0.6, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'เอาชนะ', scale = 0.6, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'BOSS BLIND', scale = 0.4, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'บอสบลายด์', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'TO RESTOCK', scale = 0.4, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'เพื่อเติมของ', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true

# การใช้แบบอักษรที่ถูกต้องสำหรับจำนวนมือ/ทิ้ง/เงิน/อันเต้ในอินเทอร์เฟซ
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'hands_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.BLUE},shadow = true, rotate = true, scale = 2*scale}),id = 'hand_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'hands_left'}}, font = G.LANGUAGES['th_TH'].font, colours = {G.C.BLUE},shadow = true, rotate = true, scale = 2*scale}),id = 'hand_UI_count'}},'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'discards_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.RED},shadow = true, rotate = true, scale = 2*scale}),id = 'discard_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'discards_left'}}, font = G.LANGUAGES['th_TH'].font, colours = {G.C.RED},shadow = true, rotate = true, scale = 2*scale}),id = 'discard_UI_count'}},'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.35, colours = {G.C.MONEY}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.8, colours = {G.C.MONEY}, font = G.LANGUAGES['th_TH'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.round_resets, ref_value = 'ante'}}, colours = {G.C.IMPORTANT},shadow = true, font = G.LANGUAGES['en-us'].font, scale = 2*scale}),id = 'ante_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.round_resets, ref_value = 'ante'}}, colours = {G.C.IMPORTANT},shadow = true, font = G.LANGUAGES['th_TH'].font, scale = 2*scale}),id = 'ante_UI_count'}},'''
overwrite = true
match_indent = true

# รองรับหลายภาษาสำหรับชื่อรวมกันเมื่อใช้ Orbital Token
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''handname= self.ability.orbital_hand,'''
position = "at"
payload = '''handname = localize(self.ability.orbital_hand, "poker_hands"),'''
overwrite = true
match_indent = true

# แก้ไขข้อความชื่อชุดในเมนูหลังการ์ดพิเศษ
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Spades', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Spades', 'suits_singular'),'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Hearts', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Hearts', 'suits_singular'),'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Clubs', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Clubs', 'suits_singular'),'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Diamonds', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Diamonds', 'suits_singular'),'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={id = 'hand_name', func = 'hand_text_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "handname_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.4})}},'''
position = "at"
payload = '''{n=G.UIT.O, config={id = 'hand_name', func = 'hand_text_UI_set',object = DynaText({string = {{ref_table = G.GAME.current_round.current_hand, ref_value = "handname_text"}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, float = true, scale = scale*1.7})}},'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''button_contents = {n=G.UIT.T, config={text = localize('b_use'),colour = G.C.WHITE, scale = 0.5}}'''
position = "at"
payload = '''button_contents = {n=G.UIT.T, config={text = localize('b_use'),colour = G.C.WHITE, scale = 0.4}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''button_contents = {n=G.UIT.T, config={text = localize('b_buy'),colour = G.C.WHITE, scale = 0.5}}'''
position = "at"
payload = '''button_contents = {n=G.UIT.T, config={text = localize('b_buy'),colour = G.C.WHITE, scale = 0.4}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={ref_table = G.GAME.blind.loc_debuff_lines, ref_value = 1, scale = scale*0.9, colour = G.C.UI.TEXT_LIGHT, id = 'HUD_blind_debuff_1', func = 'HUD_blind_debuff'}}'''
position = "at"
payload = '''{n=G.UIT.T, config={ref_table = G.GAME.blind.loc_debuff_lines, ref_value = 1, scale = scale*0.8, colour = G.C.UI.TEXT_LIGHT, id = 'HUD_blind_debuff_1', func = 'HUD_blind_debuff'}}'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={ref_table = G.GAME.blind.loc_debuff_lines, ref_value = 1, scale = scale*0.9, colour = G.C.UI.TEXT_LIGHT, id = 'HUD_blind_debuff_1', func = 'HUD_blind_debuff'}}'''
position = "at"
payload = '''{n=G.UIT.T, config={ref_table = G.GAME.blind.loc_debuff_lines, ref_value = 2, scale = scale*0.8, colour = G.C.UI.TEXT_LIGHT, id = 'HUD_blind_debuff_2', func = 'HUD_blind_debuff'}}'''
overwrite = true
match_indent = true
