name: Build

on:
  push:

env:
  MOD_ID: "85"
  GAMEID: "balatro"

permissions:
  contents: write
  packages: write

jobs:
  build-steamodded:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10

      - name: Pack mod
        run: |
          scripts/pack_steamodded.sh

      - uses: actions/upload-artifact@v4
        with:
          name: steamodded-${{ github.sha }}
          path: dist/*Steamodded.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*Steamodded.zip

      - name: Upload to Nexus
        uses: hmlendea/nexusmods-update@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          account_email_address: ${{secrets.NEXUS_UPLOADER_EMAIL_ADDRESS}}
          account_password: ${{secrets.NEXUS_UPLOADER_PASSWORD}}
          nexus_game_id: ${{env.GAMEID}}
          nexus_mod_id: ${{env.MOD_ID}}
          mod_file_name: "Steamodded Distribution"
          mod_version: ${{github.ref_name}}
          file_description: "Changelog: https://github.com/${{github.repository}}/releases/${{github.ref_name}}"
          file_path: "dist/THLocale-Steamodded.zip"

  build-standalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10

      - name: Pack mod
        run: |
          scripts/pack_standalone.sh

      - uses: actions/upload-artifact@v4
        with:
          name: standalone-${{ github.sha }}
          path: dist/*Standalone.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*Standalone.zip

      - name: Upload to Nexus
        uses: hmlendea/nexusmods-update@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          account_email_address: ${{secrets.NEXUS_UPLOADER_EMAIL_ADDRESS}}
          account_password: ${{secrets.NEXUS_UPLOADER_PASSWORD}}
          nexus_game_id: ${{env.GAMEID}}
          nexus_mod_id: ${{env.MOD_ID}}
          mod_file_name: "Standalone Distribution"
          mod_version: ${{github.ref_name}}
          file_description: "Changelog: https://github.com/${{github.repository}}/releases/${{github.ref_name}}"
          file_path: "dist/THLocale-Standalone.zip"
